/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/zombie-car/model.gltf'
  )
  const wood = useGLTF('/models/t_wood/wood.gltf')

  let angle = 0;
  const radius = 4;

  useFrame(() => {
    group.current.rotation.y -= 0.01

    group.current.position.x = radius * Math.cos(angle);
    group.current.position.z = radius * Math.sin(angle);

    angle += 0.01;
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.1}>
        <mesh
          geometry={nodes.Cylinder018_Cylinder007.geometry}
          material={wood.materials.wood_table_001}
        />
        <mesh
          geometry={nodes.Cylinder018_Cylinder007_1.geometry}
          material={materials.Windshield}
        />
      </group>
    </group>
  )
}

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/zombie-car/model.gltf'
)
